### ISSUE TITLE
Whitlist service error, cloud adapter doesn't start anymore with Admin 6

### ISSUE THREAD

**Issue by x2on** [ioBroker/ioBroker.cloud#320]
I updated to Admin 6 to enter a whitlist service (see #319), but after entering some values the following error happens:

Error: TypeError: (adapter.config.allowedServices \|\| "").split is not a function

And now the cloud adapter doesn't start.
Even if i remove the values from the whitelist.

**Comment by x2on** [comment]
Works fine with 4.2.2 - thanks for the fast fix
